### ISSUE TITLE
Not working on android?

### ISSUE THREAD

**Issue by vousys** [Pandazaur/cordova-plugin-android-mediascanner#1]
This plugin is not working on android 6. ¿?

**Comment by Pandazaur** [comment]
Hello,

I don't know it this plugin is working with Android 6. I didn't try it on this version. 

If you try with Android 6, let me know if it's working or not

**Comment by vousys** [comment]
Hi! thank you so much for your answer. 
Maybe you can help me, because I'm doing something wrong.

I'm using phonegap, cli 6.5.0
I've added the plugin to my config.xml:
    <gap:plugin name="cordova-plugin-android-mediascanner" source="git" spec="https://github.com/Pandazaur/cordova-plugin-android-mediascanner.git"/>

And then add the MediaScanner.js to my project.

Then in my code, inside the success function of "filetransfer.download"
I've tried:

MediaScanner.scanMedia( entry.toNativeURL()  ,success, err);
MediaScanner.scanMedia( entry.toURL()  ,success, err);
MediaScanner.scanMedia( entry.fullPath  ,success, err);

But I never get success or error function called.

The file downloaded exists in android storage emulated 0, but if I open the gallery or the photos gallery it didn't show it until I restart my android device.

**Comment by Pandazaur** [comment]
Are you sure "MediaScanner.js" is well imported ?
Did you `console.log(entry.toNativeUrl())` to see if it's an absolute path to your file ?

**Comment by vousys** [comment]
I guess is imported OK because I don't have any error and the line after the MediaScanner call is executed (but not my sucess function wich is an alert())

This is in y html
	<script type="text/javascript" src="cordova.js"></script>
	<script type="text/javascript" src="MediaScanner.js"></script>

The native URL is like that: file:///storage/emulated/0/MyDirectory/filename.jpg

¿Can I try anything else?

**Comment by Pandazaur** [comment]
I think you should try with the following path: `/storage/emulated/0/MyDirectory/filename.jpg` without `file://`
and try to do `console.log(MediaScanner)` to see if MediaScanner is well imported otherwise you should have an error

**Comment by vousys** [comment]
The  MediaScanner object is empty...
I don't have the physical MediaScanner.js in my project folder, I thought it cames when I add the plugin, is that right?

**Comment by Pandazaur** [comment]
No, You should download it from here and include it

**Comment by vousys** [comment]
Look I found the problem and the solution:

If I include the MediaScanner.js it fails. 

If I add only this line:	Nothing happens	
`cordova.exec(success, err, "MediaScanner", "mediaScanner", [entry.toNativeURL()]);
`
But If I add this lines, it works fine (my media index refresh and I see the folder and the file) but success or error function never gets call. Maybe you can fix it.

```
var file = "/storage/emulated/0" + entry.fullPath;
cordova.exec(success, err, "MediaScanner", "mediaScanner", [file]);

``` 
Thank you so much for your help!
